// js/movies-data.js — CineMint (22 เรื่อง)
// poster / backdrop: TMDB CDN โดยตรง — โหลดทันทีในเบราว์เซอร์ ไม่ต้องตั้งค่า API Key
// หากรูปใดโหลดไม่ขึ้น (เครือข่ายปิดกั้น TMDB) จะแสดง fallback gradient อัตโนมัติ
// เครดิต: This product uses the TMDB API but is not endorsed or certified by TMDB.

const TMDB = "https://image.tmdb.org/t/p/";

const movieDatabase = [
    {
        id: "alien-romulus",
        title: "Alien: Romulus",
        year: 2024,
        duration: "119 นาที",
        director: "Fede Álvarez",
        cast: ["Cailee Spaeny", "David Jonsson", "Archie Renaux", "Isabela Merced", "Spike Fearn"],
        genres: ["Horror", "Sci-Fi", "Thriller"],
        rating: 76,
        releaseDate: "16 ส.ค. 2024",
        status: "ฉายแล้ว",
        tmdbId: 945961,
        poster:   TMDB + "w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
        backdrop: TMDB + "w1280/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
        trailerEmbed: "https://www.youtube.com/embed/OzY2r2JXsDM",
        synopsis: "กลุ่มนักล่าอาณานิคมอวกาศรุ่นใหม่ที่พยายามหนีจากชีวิตอันสิ้นหวังบนดาวอุตสาหกรรม บุกเข้าสำรวจสถานีอวกาศร้างที่ลอยอยู่บริเวณขอบจักรวาล โดยไม่รู้เลยว่าสิ่งมีชีวิตที่อันตรายที่สุดในจักรวาลกำลังรอพวกเขาอยู่ในความมืด",
        aiReview: "Fede Álvarez พาแฟรนไชส์ Alien กลับไปสู่รากเหง้าของหนังเขย่าขวัญเอาชีวิตรอดในอวกาศได้อย่างเฉียบคม โดยไม่พึ่งพาฉากแอ็กชันใหญ่โตแบบภาคหลังๆ การออกแบบฉากภายในสถานีที่แคบ มืด และอึดอัด ช่วยขับบรรยากาศความหวาดกลัวให้เข้มข้นตลอดทั้งเรื่อง MintBot วิเคราะห์ว่าจังหวะการดำเนินเรื่องในครึ่งแรกทำหน้าที่สร้างความเชื่อมโยงกับตัวละครได้ดี ก่อนจะทิ้งทุกอย่างเข้าสู่โหมดไล่ล่าที่ตึงเครียดในช่วงท้าย Cailee Spaeny แสดงได้น่าเชื่อถือในบท Final Girl คนใหม่ของซีรีส์ แม้บางจุดของบทภาพยนตร์จะยังพึ่งพาการอ้างอิงถึงภาคต้นฉบับมากเกินไป",
        pros: ["กลับสู่รากเหง้าความเป็น Survival Horror ได้อย่างเข้มข้น", "งานออกแบบฉากและแสงสร้างความอึดอัดน่ากลัวได้ยอดเยี่ยม", "Cailee Spaeny แบกหนังได้น่าประทับใจ"],
        cons: ["Fan Service และการอ้างอิงภาคเก่ามากเกินไปในบางช่วง", "ตัวละครสมทบหลายคนมีมิติที่ค่อนข้างบาง"]
    },
    {
        id: "dune-part-two",
        title: "Dune: Part Two",
        year: 2024,
        duration: "166 นาที",
        director: "Denis Villeneuve",
        cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler", "Florence Pugh"],
        genres: ["Sci-Fi", "Adventure", "Drama"],
        rating: 92,
        releaseDate: "1 มี.ค. 2024",
        status: "ฉายแล้ว",
        tmdbId: 693134,
        poster:   TMDB + "w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        backdrop: TMDB + "w1280/ylkdrn23p3gQcHx7ukIfuy2CkTE.jpg",
        trailerEmbed: "https://www.youtube.com/embed/Way9Dexny3w",
        synopsis: "พอล อะเทรเดส รวมพลังกับชานีและชาวเฟรเมนแห่งดาวอาร์ราคิส เพื่อออกเดินทางตามล้างแค้นกลุ่มผู้สมคบคิดที่ทำลายล้างครอบครัวของเขา ท่ามกลางทางเลือกระหว่างความรักและชะตากรรมของจักรวาลทั้งมวล",
        aiReview: "ภาคต่อที่ยกระดับทุกองค์ประกอบของภาคแรกขึ้นไปอีกขั้น ทั้งสเกลของงานสร้าง การถ่ายภาพ และดนตรีประกอบของ Hans Zimmer ที่ทรงพลังจนแทบกลืนกินทุกฉาก MintBot วิเคราะห์ว่าจุดแข็งที่สุดของหนังคือการค่อยๆ พาผู้ชมเข้าสู่ความซับซ้อนทางศีลธรรมของพอลในฐานะผู้นำที่กำลังเดินเข้าสู่เส้นทางของผู้กดขี่ ไม่ใช่วีรบุรุษแบบขาวสะอาด ฉากขี่หนอนทรายและสงครามในทะเลทรายถูกถ่ายทำอย่างพิถีพิถันจนกลายเป็นหนึ่งในภาพจำของวงการไซไฟยุคใหม่",
        pros: ["งานภาพและซาวด์ดีไซน์ระดับมาสเตอร์พีซ", "การพัฒนาตัวละครพอลในเชิงศีลธรรมที่ลึกซึ้ง", "ฉากแอ็กชันสเกลยักษ์ที่กำกับได้สมจริง"],
        cons: ["ความยาวและความหนาแน่นของเนื้อเรื่องอาจไม่เป็นมิตรกับผู้ชมหน้าใหม่", "จังหวะหนังในช่วงกลางเรื่องค่อนข้างหน่วง"]
    },
    {
        id: "inside-out-2",
        title: "Inside Out 2",
        year: 2024,
        duration: "96 นาที",
        director: "Kelsey Mann",
        cast: ["Amy Poehler", "Maya Hawke", "Kensington Tallman", "Tony Hale", "Lewis Black"],
        genres: ["Animation", "Family", "Comedy"],
        rating: 88,
        releaseDate: "14 มิ.ย. 2024",
        status: "ฉายแล้ว",
        tmdbId: 1022789,
        poster:   TMDB + "w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        backdrop: TMDB + "w1280/qbhS3PeM7EX8bMSXtKZeFOQ6Dkk.jpg",
        trailerEmbed: "https://www.youtube.com/embed/s3vmaTtugfU",
        synopsis: "ไรลีย์ก้าวเข้าสู่วัยรุ่นพร้อมกับอารมณ์ใหม่ที่ถาโถมเข้ามาในศูนย์บัญชาการความคิด นำโดยความวิตกกังวลที่ต้องการเข้ามาควบคุมทุกอย่าง",
        aiReview: "ภาคต่อที่กล้าเผชิญหน้ากับหัวข้อที่ซับซ้อนกว่าเดิมอย่างความวิตกกังวลในวัยรุ่น โดยไม่ลดทอนความสนุกแบบแอนิเมชันครอบครัว MintBot ประเมินว่าการสร้างตัวละคร 'วิตกกังวล' ให้มีทั้งด้านที่น่ารำคาญและด้านที่น่าเห็นใจในเวลาเดียวกัน เป็นการเขียนบทที่ละเอียดอ่อนและตรงกับประสบการณ์จริงของผู้ชมวัยรุ่นจำนวนมาก งานภาพยังคงความคิดสร้างสรรค์ในการแปลงนามธรรมทางจิตวิทยาให้กลายเป็นภาพที่เข้าใจง่าย",
        pros: ["นำเสนอเรื่องความวิตกกังวลในวัยรุ่นได้ลึกซึ้งและเข้าใจง่าย", "งานภาพและจินตนาการสร้างสรรค์ระดับพิกซาร์", "อารมณ์ขันและฉากซึ้งสมดุลกันอย่างลงตัว"],
        cons: ["ตัวละครอารมณ์ชุดเดิมได้พื้นที่น้อยลงกว่าที่ควร", "ช่วงท้ายเร่งสรุปเร็วไปสักหน่อย"]
    },
    {
        id: "civil-war-2024",
        title: "Civil War",
        year: 2024,
        duration: "109 นาที",
        director: "Alex Garland",
        cast: ["Kirsten Dunst", "Wagner Moura", "Cailee Spaeny", "Stephen McKinley Henderson"],
        genres: ["Action", "Drama", "Thriller"],
        rating: 75,
        releaseDate: "12 เม.ย. 2024",
        status: "ฉายแล้ว",
        tmdbId: 929590,
        poster:   TMDB + "w500/fc9eFMBgFjqFBB9ZE7gRBIXBaZZ.jpg",
        backdrop: TMDB + "w1280/9mNBMFb9dqVfO15bJDpHmSTuF7J.jpg",
        trailerEmbed: "https://www.youtube.com/embed/aDyQxtg0V2w",
        synopsis: "ทีมช่างภาพข่าวสงครามเดินทางข้ามประเทศสหรัฐอเมริกาที่กำลังแตกแยกด้วยสงครามกลางเมือง มุ่งหน้าสู่วอชิงตัน ดี.ซี. เพื่อบันทึกภาพประวัติศาสตร์ครั้งสำคัญ",
        aiReview: "Alex Garland เลือกที่จะไม่อธิบายต้นตอทางการเมืองของสงครามอย่างชัดเจน แต่โฟกัสไปที่ประสบการณ์ของนักข่าวภาคสนามที่ต้องอยู่ระหว่างความเป็นกลางทางวิชาชีพกับความรุนแรงตรงหน้า MintBot มองว่าการตัดสินใจนี้ทำให้หนังกลายเป็นบทสนทนาว่าด้วยจริยธรรมของสื่อมากกว่าจะเป็นหนังการเมืองแบบตรงไปตรงมา",
        pros: ["งานภาพและเสียงสมจริงจนสร้างความอึดอัดได้อย่างทรงพลัง", "การแสดงของ Kirsten Dunst ที่นิ่งและลึกซึ้ง", "มุมมองที่แปลกใหม่ต่อหนังแนวสงครามกลางเมือง"],
        cons: ["หลีกเลี่ยงบริบททางการเมืองจนบางครั้งรู้สึกคลุมเครือเกินไป", "การพัฒนาตัวละครสมทบยังไม่ลึกพอ"]
    },
    {
        id: "the-batman",
        title: "The Batman",
        year: 2022,
        duration: "176 นาที",
        director: "Matt Reeves",
        cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Jeffrey Wright", "Colin Farrell"],
        genres: ["Action", "Crime", "Mystery"],
        rating: 85,
        releaseDate: "4 มี.ค. 2022",
        status: "ฉายแล้ว",
        tmdbId: 414906,
        poster:   TMDB + "w500/74xTEgt7R36Fpocon6VOudiJPDd.jpg",
        backdrop: TMDB + "w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
        trailerEmbed: "https://www.youtube.com/embed/mqqft2x_Aa4",
        synopsis: "ในปีที่สองของการสวมบทบาทเป็นมือปราบอาชญากรรม บรูซ เวย์น ต้องสืบสวนคดีฆาตกรรมต่อเนื่องที่เชื่อมโยงกับการทุจริตในเมืองก็อตแธม",
        aiReview: "Matt Reeves นำเสนอ Batman ในมุมที่เป็นหนังสืบสวนสอบสวนแบบฟิล์มนัวร์มากกว่าหนังซูเปอร์ฮีโร่ทั่วไป โทนภาพที่มืดทึบและเปียกฝนตลอดเรื่องสร้างบรรยากาศก็อตแธมที่สมจริงและน่าขนลุก MintBot วิเคราะห์ว่าความยาวเกือบสามชั่วโมงถูกใช้ไปกับการคลี่คลายปริศนาทีละชั้นอย่างมีชั้นเชิง",
        pros: ["บรรยากาศฟิล์มนัวร์ที่สร้างก็อตแธมได้สมจริงและน่าจดจำ", "การแสดงของ Paul Dano ในบทวายร้ายที่น่าขนลุก", "บทสืบสวนที่คลี่คลายปริศนาอย่างมีชั้นเชิง"],
        cons: ["ความยาวเกือบสามชั่วโมงอาจรู้สึกหน่วงในบางช่วง", "โทนหนังที่หม่นมืดตลอดเรื่องอาจไม่เหมาะกับทุกคน"]
    },
    {
        id: "parasite",
        title: "Parasite",
        year: 2019,
        duration: "132 นาที",
        director: "Bong Joon-ho",
        cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik", "Park So-dam"],
        genres: ["Drama", "Thriller", "Black Comedy"],
        rating: 98,
        releaseDate: "30 พ.ค. 2019",
        status: "ฉายแล้ว",
        tmdbId: 496243,
        poster:   TMDB + "w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        backdrop: TMDB + "w1280/ApiBzeaa95TNYLDouKAt1RQDxRl.jpg",
        trailerEmbed: "https://www.youtube.com/embed/QRkBjCGJ3Uc",
        synopsis: "ครอบครัวคิมที่ยากจนและตกงานทั้งครอบครัว ค่อยๆ แทรกซึมเข้าไปทำงานในบ้านของครอบครัวพักผู้มั่งคั่งทีละคน จนเกิดความสัมพันธ์ที่ซับซ้อนซึ่งนำไปสู่เหตุการณ์ที่ไม่มีใครคาดคิด",
        aiReview: "ผลงานชิ้นเอกของ Bong Joon-ho ที่ผสมผสานหนังตลกร้าย ดราม่าครอบครัว และระทึกขวัญเข้าด้วยกันได้อย่างไร้รอยต่อ MintBot วิเคราะห์ว่าสถาปัตยกรรมของบ้านสองหลังในเรื่องถูกใช้เป็นสัญลักษณ์แทนช่องว่างทางชนชั้นได้อย่างชาญฉลาด ทุกฉากมีรายละเอียดที่ซ่อนความหมายเชิงสังคมไว้อย่างแยบยล โครงเรื่องที่พลิกผันในครึ่งหลังเปลี่ยนโทนหนังอย่างไม่มีใครคาดเดาได้",
        pros: ["บทภาพยนตร์และโครงสร้างเรื่องที่ฉลาดและแน่นไร้ที่ติ", "สัญลักษณ์เชิงสังคมที่ซ่อนอยู่ในทุกรายละเอียดของฉาก", "การแสดงของนักแสดงทุกคนสมจริงและทรงพลัง"],
        cons: ["จังหวะการเปลี่ยนโทนหนังในครึ่งหลังอาจทำให้ผู้ชมบางส่วนตั้งตัวไม่ทัน", "ความหมายเชิงสัญลักษณ์ที่แน่นมากอาจต้องดูซ้ำเพื่อจับรายละเอียดให้ครบ"]
    },
    {
        id: "anatomy-of-a-fall",
        title: "Anatomy of a Fall",
        year: 2023,
        duration: "152 นาที",
        director: "Justine Triet",
        cast: ["Sandra Hüller", "Swann Arlaud", "Milo Machado-Graner", "Antoine Reinartz"],
        genres: ["Drama", "Mystery", "Courtroom"],
        rating: 95,
        releaseDate: "13 ต.ค. 2023",
        status: "ฉายแล้ว",
        tmdbId: 915935,
        poster:   TMDB + "w500/aqgNkJVTCbHPkyON1SjgLEMSMCB.jpg",
        backdrop: TMDB + "w1280/1XOhP4ELSHacVEJLnOqjF1XMZAK.jpg",
        trailerEmbed: "https://www.youtube.com/embed/wYE1ekxtCJ8",
        synopsis: "นักเขียนหญิงตกเป็นผู้ต้องสงสัยในคดีการเสียชีวิตปริศนาของสามีที่บ้านพักกลางเทือกเขาแอลป์ โดยมีลูกชายตาบอดวัยสิบเอ็ดขวบเป็นพยานเพียงคนเดียว",
        aiReview: "Justine Triet สร้างหนังศาลที่ไม่ได้สนใจคำตัดสินสุดท้ายมากเท่ากับความจริงที่ไม่มีวันรู้ได้แน่ชัดในความสัมพันธ์ของมนุษย์ MintBot ประเมินว่าบทสนทนาในห้องพิจารณาคดีถูกเขียนอย่างเฉียบคม ทุกประโยคทำหน้าที่เปิดเผยทั้งข้อเท็จจริงของคดีและบาดแผลภายในชีวิตคู่ไปพร้อมกัน Sandra Hüller แสดงได้ซับซ้อนจนผู้ชมไม่อาจตัดสินได้ง่ายๆ",
        pros: ["บทภาพยนตร์ห้องพิจารณาคดีที่เฉียบคมและสมจริง", "การแสดงของ Sandra Hüller ที่ซับซ้อนระดับรางวัล", "เปิดให้ผู้ชมตีความและตัดสินด้วยตัวเอง"],
        cons: ["ความยาวกว่าสองชั่วโมงครึ่งที่เน้นบทสนทนาอาจรู้สึกล้าในบางช่วง", "จังหวะการเล่าเรื่องช้าอาจไม่เหมาะกับผู้ที่ชอบหนังกระชับ"]
    },
    {
        id: "oppenheimer",
        title: "Oppenheimer",
        year: 2023,
        duration: "180 นาที",
        director: "Christopher Nolan",
        cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr.", "Florence Pugh"],
        genres: ["Biography", "Drama", "History"],
        rating: 96,
        releaseDate: "21 ก.ค. 2023",
        status: "ฉายแล้ว",
        tmdbId: 872585,
        poster:   TMDB + "w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
        backdrop: TMDB + "w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
        trailerEmbed: "https://www.youtube.com/embed/LZq9kSRwfkg",
        synopsis: "เรื่องราวชีวิตของเจ. โรเบิร์ต ออพเพนไฮเมอร์ นักฟิสิกส์ทฤษฎีผู้นำทีมพัฒนาระเบิดปรมาณูในโครงการแมนฮัตตัน และความขัดแย้งภายในจิตใจที่ต้องแบกรับตลอดชีวิต",
        aiReview: "Christopher Nolan ใช้โครงสร้างการเล่าเรื่องแบบสลับเวลาไปมาอย่างกล้าหาญ เพื่อถ่ายทอดความซับซ้อนทางจิตใจของชายผู้ได้รับฉายาว่า 'บิดาแห่งระเบิดปรมาณู' MintBot วิเคราะห์ว่าฉากการทดลองระเบิดที่ทรินิตี้ถูกถ่ายทำด้วยเทคนิคจริงโดยไม่พึ่ง CGI สร้างความตึงเครียดที่หาตัวจับยากในประวัติศาสตร์ภาพยนตร์",
        pros: ["การแสดงของ Cillian Murphy ที่ทรงพลังระดับรางวัลออสการ์", "เทคนิคการถ่ายทำฉากระเบิดด้วยวิธีจริงที่น่าทึ่ง", "ดนตรีประกอบและงานตัดต่อที่สร้างความตึงเครียดได้ยอดเยี่ยม"],
        cons: ["โครงสร้างเรื่องสลับเวลาอาจทำให้ผู้ชมบางส่วนสับสน", "บทสนทนาทางการเมืองที่หนาแน่นต้องอาศัยสมาธิสูง"]
    },
    {
        id: "poor-things",
        title: "Poor Things",
        year: 2023,
        duration: "141 นาที",
        director: "Yorgos Lanthimos",
        cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe", "Ramy Youssef"],
        genres: ["Comedy", "Drama", "Sci-Fi"],
        rating: 90,
        releaseDate: "8 ธ.ค. 2023",
        status: "ฉายแล้ว",
        tmdbId: 792307,
        poster:   TMDB + "w500/kCGlIMHnOm8JPXEaM7X9Rnzw13t.jpg",
        backdrop: TMDB + "w1280/cGXExt9MHbCMFfCJGMqrEyNNfbO.jpg",
        trailerEmbed: "https://www.youtube.com/embed/1f4aXbF1pCc",
        synopsis: "เบลล่า แบ็กซ์เตอร์ หญิงสาวที่ถูกชุบชีวิตขึ้นใหม่โดยนักวิทยาศาสตร์สติเฟื่อง ออกเดินทางสำรวจโลกกว้างด้วยมุมมองที่ไร้เดียงสาแต่เปี่ยมความอยากรู้อยากเห็น",
        aiReview: "Yorgos Lanthimos สร้างโลกแฟนตาซีที่แปลกประหลาดแต่งดงามอย่างน่าทึ่ง MintBot วิเคราะห์ว่าการแสดงของ Emma Stone คือหัวใจสำคัญที่ทำให้หนังประสบความสำเร็จ เธอถ่ายทอดพัฒนาการของเบลล่าตั้งแต่ขั้นทารกไปจนถึงผู้หญิงที่ตื่นรู้ทางความคิดได้อย่างกล้าหาญและไร้ที่ติ",
        pros: ["งานโปรดักชันดีไซน์และภาพที่สร้างสรรค์ระดับมาสเตอร์พีซ", "การแสดงของ Emma Stone ที่กล้าหาญและทรงพลัง", "การเล่าเรื่องเชิงเสียดสีสังคมที่ฉลาดและมีเอกลักษณ์"],
        cons: ["เนื้อหาและภาพในบางฉากค่อนข้างตรงไปตรงมา ไม่เหมาะกับผู้ชมทุกวัย", "จังหวะการเล่าเรื่องที่แปลกอาจไม่ถูกใจทุกคน"]
    },
    {
        id: "furiosa-mad-max",
        title: "Furiosa: A Mad Max Saga",
        year: 2024,
        duration: "148 นาที",
        director: "George Miller",
        cast: ["Anya Taylor-Joy", "Chris Hemsworth", "Tom Burke", "Alyla Browne"],
        genres: ["Action", "Adventure", "Sci-Fi"],
        rating: 84,
        releaseDate: "24 พ.ค. 2024",
        status: "ฉายแล้ว",
        tmdbId: 786892,
        poster:   TMDB + "w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
        backdrop: TMDB + "w1280/phEr2VCY9k3Db8QQ7hzZNrVIRCp.jpg",
        trailerEmbed: "https://www.youtube.com/embed/Mp1NszGIuNo",
        synopsis: "เรื่องราวต้นกำเนิดของฟิวริโอซ่า เมื่อเธอถูกลักพาตัวจากดินแดนสีเขียวในวัยเด็ก และต้องดิ้นรนเอาชีวิตรอดท่ามกลางขุนศึกผู้โหดร้ายในโลกที่ล่มสลาย",
        aiReview: "George Miller ยังคงรักษามาตรฐานแอ็กชันสไตล์ Mad Max ที่ดิบ บ้าคลั่ง และเต็มไปด้วยจินตนาการเหนือจริงได้อย่างน่าทึ่ง MintBot วิเคราะห์ว่าโครงสร้างหนังในรูปแบบมหากาพย์ย้อนอดีตที่แบ่งเป็นบทต่างๆ ช่วยให้เรื่องราวต้นกำเนิดของฟิวริโอซ่ามีน้ำหนักทางอารมณ์มากกว่าที่คาดไว้",
        pros: ["ฉากแอ็กชัน Practical Effect ที่สมจริงและตื่นตาตื่นใจ", "การแสดงของ Chris Hemsworth ในบทวายร้ายที่น่าจดจำ", "โลกดิสโทเปียที่สร้างสรรค์อย่างมีรายละเอียด"],
        cons: ["เทียบกับ Fury Road แล้วความเข้มข้นโดยรวมลดลงเล็กน้อย", "ช่วงกลางเรื่องมีจังหวะที่หน่วงกว่าที่คาดไว้"]
    },
    {
        id: "godzilla-x-kong",
        title: "Godzilla x Kong: The New Empire",
        year: 2024,
        duration: "115 นาที",
        director: "Adam Wingard",
        cast: ["Rebecca Hall", "Brian Tyree Henry", "Dan Stevens", "Kaylee Hottle"],
        genres: ["Action", "Sci-Fi", "Adventure"],
        rating: 68,
        releaseDate: "29 มี.ค. 2024",
        status: "ฉายแล้ว",
        tmdbId: 823464,
        poster:   TMDB + "w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
        backdrop: TMDB + "w1280/4YZpsylmjHbqeWzjKpUEF8gcLNW.jpg",
        trailerEmbed: "https://www.youtube.com/embed/x48TIclKWgU",
        synopsis: "ก็อดซิลล่าและคองต้องจับมือกันเป็นพันธมิตร เพื่อปกป้องโลกจากภัยคุกคามครั้งใหม่ที่ซ่อนตัวอยู่ในดินแดนกลวงใต้พิภพ",
        aiReview: "หนังในจักรวาล MonsterVerse ภาคนี้เลือกที่จะทุ่มงบประมาณไปกับฉากต่อสู้ระหว่างสัตว์ประหลาดเป็นหลัก โดยลดทอนความสำคัญของเส้นเรื่องมนุษย์ลงอย่างชัดเจน MintBot วิเคราะห์ว่าฉากแอ็กชันแต่ละฉากถูกออกแบบมาให้ตื่นตาตื่นใจและเหมาะกับจอไอแมกซ์",
        pros: ["ฉากต่อสู้ระหว่างไททันสเกลใหญ่ที่ตื่นตาตื่นใจ", "งานเทคนิค CGI และดีไซน์มอนสเตอร์ที่ประณีต", "ความบันเทิงแบบเบาสมองที่ดูสนุกได้ทั้งครอบครัว"],
        cons: ["บทภาพยนตร์และเส้นเรื่องมนุษย์ค่อนข้างบางและคาดเดาได้", "ขาดความลึกทางอารมณ์เมื่อเทียบกับภาคอื่นในจักรวาลเดียวกัน"]
    },
    {
        id: "deadpool-wolverine",
        title: "Deadpool & Wolverine",
        year: 2024,
        duration: "128 นาที",
        director: "Shawn Levy",
        cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Matthew Macfadyen"],
        genres: ["Action", "Comedy", "Sci-Fi"],
        rating: 80,
        releaseDate: "26 ก.ค. 2024",
        status: "ฉายแล้ว",
        tmdbId: 533535,
        poster:   TMDB + "w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        backdrop: TMDB + "w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        trailerEmbed: "https://www.youtube.com/embed/73_1biulkYk",
        synopsis: "เวด วิลสัน ถูกดึงเข้าสู่ภารกิจที่ต้องจับมือกับวูล์ฟเวอรีนจากจักรวาลคู่ขนาน ท่ามกลางมุกตลกแหลกลาญและการอ้างอิงจักรวาล Marvel แบบไม่ยั้ง",
        aiReview: "หนังที่รู้ตัวว่าตัวเองคือหนังคอเมดี้เสียดสีจักรวาล Marvel และเล่นกับจุดนั้นได้อย่างสนุกสนานเต็มที่ MintBot วิเคราะห์ว่าเคมีระหว่าง Ryan Reynolds และ Hugh Jackman คือแกนหลักที่ทำให้หนังสนุกตลอดทั้งเรื่อง",
        pros: ["เคมีระหว่าง Ryan Reynolds และ Hugh Jackman ที่สนุกและลงตัว", "มุกตลกหนาแน่นและจังหวะการเล่าเรื่องที่กระชับ", "ฉากแอ็กชันที่ออกแบบให้เข้ากับบุคลิกตัวละคร"],
        cons: ["มุกอ้างอิงจักรวาล Marvel หนาแน่นเกินไปสำหรับผู้ชมทั่วไป", "เนื้อเรื่องหลักค่อนข้างเรียบง่ายเมื่อเทียบกับมุกตลกที่มี"]
    },
    {
        id: "everything-everywhere",
        title: "Everything Everywhere All at Once",
        year: 2022,
        duration: "140 นาที",
        director: "Daniel Kwan, Daniel Scheinert",
        cast: ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu", "Jamie Lee Curtis", "James Hong"],
        genres: ["Sci-Fi", "Action", "Comedy"],
        rating: 94,
        releaseDate: "8 เม.ย. 2022",
        status: "ฉายแล้ว",
        tmdbId: 545611,
        poster:   TMDB + "w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        backdrop: TMDB + "w1280/fepODRwVvN9YaQz9TDp5q3KNcPJ.jpg",
        trailerEmbed: "https://www.youtube.com/embed/jtJ5crAEpmk",
        synopsis: "เอเวอลิน เจ้าของร้านซักรีดผู้อพยพชาวจีน ถูกดึงเข้าสู่การผจญภัยข้ามจักรวาลคู่ขนาน เมื่อค้นพบว่าตัวเองเป็นความหวังเดียวที่จะหยุดยั้งหายนะที่คุกคามทุกจักรวาล",
        aiReview: "ผลงานที่กล้าหาญที่สุดเรื่องหนึ่งของวงการไซไฟยุคใหม่ ผสมความบ้าคลั่งของมัลติเวิร์สเข้ากับดราม่าครอบครัวผู้อพยพได้อย่างไม่น่าเชื่อว่าจะเวิร์ก MintBot วิเคราะห์ว่าความเก่งของ Daniels คือการใช้ความโกลาหลทางภาพเป็นเพียงเปลือกนอก แก่นแท้คือความสัมพันธ์แม่ลูกที่เจ็บปวดและอบอุ่นในเวลาเดียวกัน",
        pros: ["ไอเดียมัลติเวิร์สที่สร้างสรรค์และไม่เหมือนใคร", "แก่นเรื่องครอบครัวที่ลึกซึ้งและสะเทือนใจ", "การแสดงของ Michelle Yeoh และ Ke Huy Quan ยอดเยี่ยม"],
        cons: ["ความหนาแน่นของภาพและไอเดียอาจทำให้ผู้ชมเหนื่อยล้าในบางช่วง", "โทนเรื่องที่สลับไปมาเร็วอาจไม่เหมาะกับทุกคน"]
    },
    {
        id: "la-la-land",
        title: "La La Land",
        year: 2016,
        duration: "128 นาที",
        director: "Damien Chazelle",
        cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
        genres: ["Musical", "Romance", "Drama"],
        rating: 89,
        releaseDate: "9 ธ.ค. 2016",
        status: "ฉายแล้ว",
        tmdbId: 313369,
        poster:   TMDB + "w500/uDO8zWDhfWwoFdKS4fzkUJt0Bs0.jpg",
        backdrop: TMDB + "w1280/nadTlnTE5DgGMGgSEMKZPkCKMWR.jpg",
        trailerEmbed: "https://www.youtube.com/embed/0pdqf4P9MB8",
        synopsis: "มีอา นักแสดงสาวผู้ใฝ่ฝัน และเซบาสเตียน นักเปียโนแจ๊ส พบรักกันท่ามกลางเมืองลอสแอนเจลิส แต่เมื่อความสำเร็จเริ่มเข้ามา ทั้งคู่ต้องเลือกระหว่างความรักและความฝัน",
        aiReview: "Damien Chazelle สร้างหนังเพลงที่เคารพขนบของหนังมิวสิคัลคลาสสิกฮอลลีวูดยุคทอง ขณะเดียวกันก็ใส่ความเศร้าแบบร่วมสมัยเข้าไปอย่างกล้าหาญ MintBot วิเคราะห์ว่าฉากเปิดเรื่องบนทางด่วนและฉากเต้นรำท่ามกลางพระอาทิตย์ตกคือตัวอย่างของการกำกับที่เปี่ยมความมั่นใจ ตอนจบที่กล้าเลือกความสมจริงเหนือความสมหวังคือสิ่งที่ทำให้หนังนี้อยู่ในความทรงจำ",
        pros: ["งานกำกับและถ่ายภาพที่สง่างามแบบหนังมิวสิคัลคลาสสิก", "เคมีระหว่าง Ryan Gosling และ Emma Stone ที่น่าประทับใจ", "ตอนจบที่กล้าหาญและสมจริงทางอารมณ์"],
        cons: ["บทเพลงบางเพลงอาจไม่ติดหูเท่าที่คาดหวัง", "เนื้อเรื่องค่อนข้างคุ้นเคยสำหรับแฟนหนังโรแมนติกดราม่า"]
    },
    {
        id: "spider-verse-across",
        title: "Spider-Man: Across the Spider-Verse",
        year: 2023,
        duration: "140 นาที",
        director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
        cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Jake Johnson", "Issa Rae"],
        genres: ["Animation", "Action", "Sci-Fi"],
        rating: 93,
        releaseDate: "2 มิ.ย. 2023",
        status: "ฉายแล้ว",
        tmdbId: 569094,
        poster:   TMDB + "w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        backdrop: TMDB + "w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        trailerEmbed: "https://www.youtube.com/embed/UUqUZ7uumqE",
        synopsis: "ไมล์ส โมราเลส กลับมาพบกับเกวน สเตซีย์อีกครั้ง ก่อนจะถูกพาตัวข้ามมัลติเวิร์สไปพบกับสมาคมสไปเดอร์ แต่เมื่อความเชื่อของเขาขัดแย้งกับกฎของสมาคม เขาต้องเลือกเส้นทางของตัวเอง",
        aiReview: "ภาคต่อที่ยกระดับงานแอนิเมชันให้กลายเป็นงานศิลปะร่วมสมัยอย่างแท้จริง แต่ละจักรวาลในเรื่องมีสไตล์ภาพเฉพาะตัวที่แตกต่างกันอย่างสิ้นเชิง MintBot วิเคราะห์ว่าความกล้าทางภาพนี้สะท้อนธีมเรื่องอัตลักษณ์และการเลือกชะตากรรมของตัวเองได้อย่างแยบยล",
        pros: ["งานแอนิเมชันที่สร้างสรรค์และหลากหลายสไตล์อย่างน่าทึ่ง", "การพัฒนาตัวละครไมล์สที่ลึกซึ้งและมีน้ำหนัก", "ดนตรีประกอบและจังหวะตัดต่อที่ทรงพลัง"],
        cons: ["ตอนจบแบบค้างเรื่องอาจทำให้ผู้ชมรู้สึกไม่สมบูรณ์", "ความยาวและความหนาแน่นของเนื้อเรื่องอาจมากเกินไปสำหรับเด็กเล็ก"]
    },
    {
        id: "grand-budapest-hotel",
        title: "The Grand Budapest Hotel",
        year: 2014,
        duration: "100 นาที",
        director: "Wes Anderson",
        cast: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan", "Adrien Brody", "Willem Dafoe"],
        genres: ["Comedy", "Drama", "Adventure"],
        rating: 87,
        releaseDate: "7 มี.ค. 2014",
        status: "ฉายแล้ว",
        tmdbId: 120467,
        poster:   TMDB + "w500/nX5XotM9yprCKarRH4fzOq1VM1J.jpg",
        backdrop: TMDB + "w1280/bkX3poBM8Ov8jsXUTmJ4SPnX3IF.jpg",
        trailerEmbed: "https://www.youtube.com/embed/1Fg5iWmQjwk",
        synopsis: "เรื่องราวการผจญภัยของกุสตาฟ เอช คอนเซียร์จผู้เก๋าไก๋แห่งโรงแรมสุดหรูในยุโรปและซีโร่ ลูกน้องหนุ่มของเขา เมื่อทั้งคู่พัวพันกับคดีโจรกรรมภาพวาดล้ำค่า",
        aiReview: "Wes Anderson นำเสนอจักรวาลสมมาตรอันเป็นเอกลักษณ์ของตัวเองได้อย่างสมบูรณ์แบบที่สุดเรื่องหนึ่งในผลงานทั้งหมด ทั้งโทนสีพาสเทล องค์ประกอบภาพที่จัดวางอย่างพิถีพิถัน และจังหวะตัดต่อที่กระชับฉับไว MintBot วิเคราะห์ว่าใต้ความตลกขบขัน หนังยังซ่อนความเศร้าเกี่ยวกับการล่มสลายของอารยธรรมยุโรปก่อนสงครามไว้อย่างแยบยล",
        pros: ["งานภาพและองค์ประกอบศิลป์ที่เป็นเอกลักษณ์ระดับมาสเตอร์พีซ", "การแสดงของ Ralph Fiennes ที่ยอดเยี่ยมและน่าจดจำ", "อารมณ์ขันแบบ Deadpan ที่ผสมความเศร้าได้อย่างลงตัว"],
        cons: ["สไตล์ภาพที่จัดจ้านมากอาจไม่เหมาะกับผู้ชมที่ชอบความสมจริง", "โครงเรื่องที่ซ้อนหลายชั้นอาจทำให้ตามยากในช่วงแรก"]
    },
    {
        id: "interstellar",
        title: "Interstellar",
        year: 2014,
        duration: "169 นาที",
        director: "Christopher Nolan",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        genres: ["Sci-Fi", "Adventure", "Drama"],
        rating: 91,
        releaseDate: "5 พ.ย. 2014",
        status: "ฉายแล้ว",
        tmdbId: 157336,
        poster:   TMDB + "w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        backdrop: TMDB + "w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
        trailerEmbed: "https://www.youtube.com/embed/2LqzF5WauAw",
        synopsis: "คูเปอร์ อดีตนักบินนาซ่า ต้องทิ้งครอบครัวไว้เบื้องหลังเพื่อนำทีมนักสำรวจออกเดินทางผ่านรูหนอนในอวกาศ ตามหาดาวเคราะห์ดวงใหม่ที่จะเป็นบ้านหลังใหม่ของมนุษยชาติ",
        aiReview: "Christopher Nolan สร้างมหากาพย์ไซไฟที่ผสมผสานความรู้ทางฟิสิกส์เชิงทฤษฎีเข้ากับดราม่าความสัมพันธ์พ่อลูกได้อย่างทรงพลัง MintBot วิเคราะห์ว่าจุดแข็งที่สุดคือการทำให้แนวคิดเรื่องสัมพัทธภาพเวลาและหลุมดำกลายเป็นเครื่องมือเล่าเรื่องทางอารมณ์ ไม่ใช่แค่ฉากโชว์วิทยาศาสตร์",
        pros: ["แนวคิดวิทยาศาสตร์ที่ลึกซึ้งผสานกับดราม่าครอบครัวได้อย่างลงตัว", "งานภาพและดนตรีประกอบของ Hans Zimmer ที่ยิ่งใหญ่อลังการ", "การแสดงของ Matthew McConaughey ที่สะเทือนอารมณ์"],
        cons: ["บทสนทนาเชิงวิทยาศาสตร์ในช่วงท้ายอาจเข้าใจยากสำหรับบางคน", "ความยาวเกือบสามชั่วโมงอาจรู้สึกหนักในบางช่วง"]
    },
    {
        id: "whiplash",
        title: "Whiplash",
        year: 2014,
        duration: "106 นาที",
        director: "Damien Chazelle",
        cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
        genres: ["Drama", "Music"],
        rating: 90,
        releaseDate: "10 ต.ค. 2014",
        status: "ฉายแล้ว",
        tmdbId: 244786,
        poster:   TMDB + "w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        backdrop: TMDB + "w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
        trailerEmbed: "https://www.youtube.com/embed/Df1xkYYbYrY",
        synopsis: "แอนดรูว์ นักเรียนกลองแจ๊สผู้มุ่งมั่น เข้าสู่วงดนตรีชั้นนำภายใต้การฝึกสอนของฟลีทเชอร์ ครูผู้เข้มงวดและโหดร้ายอย่างถึงที่สุด ความปรารถนาในความสมบูรณ์แบบของทั้งคู่ขับเคี่ยวกันถึงขีดสุด",
        aiReview: "Damien Chazelle สร้างหนังดราม่าเกี่ยวกับดนตรีที่ตึงเครียดราวกับหนังระทึกขวัญ MintBot วิเคราะห์ว่าการตัดต่อจังหวะเร็วที่สลับไปมาในฉากซ้อมดนตรีสร้างความกดดันที่จับต้องได้แทบทุกวินาที J.K. Simmons แสดงได้น่าสะพรึงกลัวอย่างแท้จริง ฉากไคลแม็กซ์ในช่วงท้ายคือหนึ่งในฉากที่ทรงพลังที่สุดในหนังดราม่ายุคใหม่",
        pros: ["การแสดงของ J.K. Simmons ที่น่าสะพรึงกลัวระดับรางวัลออสการ์", "งานตัดต่อที่สร้างความตึงเครียดได้อย่างทรงพลัง", "ฉากไคลแม็กซ์ที่ทรงพลังและน่าจดจำที่สุดเรื่องหนึ่ง"],
        cons: ["แนวทางการสอนที่โหดร้ายในเรื่องอาจสร้างความไม่สบายใจให้ผู้ชมบางกลุ่ม", "ตัวละครรองอย่างครอบครัวและแฟนสาวได้พื้นที่น้อยมาก"]
    },
    {
        id: "knives-out",
        title: "Knives Out",
        year: 2019,
        duration: "130 นาที",
        director: "Rian Johnson",
        cast: ["Daniel Craig", "Chris Evans", "Ana de Armas", "Jamie Lee Curtis", "Toni Collette"],
        genres: ["Mystery", "Comedy", "Crime"],
        rating: 86,
        releaseDate: "27 พ.ย. 2019",
        status: "ฉายแล้ว",
        tmdbId: 546554,
        poster:   TMDB + "w500/pThyQovXQrpS44oZn0MksPsTEQs.jpg",
        backdrop: TMDB + "w1280/dg8BNvPwvAjHKFeFzDQV2s16E5V.jpg",
        trailerEmbed: "https://www.youtube.com/embed/9jxUXqPmwOE",
        synopsis: "เมื่อนักเขียนนิยายอาชญากรรมชื่อดังเสียชีวิตอย่างปริศนาในคฤหาสน์ของตัวเอง นักสืบเบอนัวต์ บล็องก์ถูกเรียกตัวมาสืบสวน ท่ามกลางสมาชิกครอบครัวสุดป่วนที่ต่างมีเหตุผลต้องการให้เขาตาย",
        aiReview: "Rian Johnson เขียนบทหนังฆาตกรรมปริศนาที่เคารพขนบของ Agatha Christie แต่ใส่มุมมองทางสังคมร่วมสมัยเข้าไปอย่างชาญฉลาด MintBot วิเคราะห์ว่าโครงสร้างเรื่องที่เปิดเผยส่วนหนึ่งของความจริงตั้งแต่กลางเรื่องเป็นการเล่นกับขนบของแนวฆาตกรรมปริศนาได้อย่างสร้างสรรค์ Ana de Armas แบกหนังในฐานะตัวละครหลักได้อย่างน่าประทับใจ",
        pros: ["บทภาพยนตร์ที่ฉลาดและเล่นกับขนบหนังฆาตกรรมปริศนาได้อย่างสร้างสรรค์", "นักแสดงทั้งวงเล่นสนุกและเข้ากับบทบาทอย่างยอดเยี่ยม", "มุมมองเสียดสีสังคมที่แทรกอยู่อย่างแยบยล"],
        cons: ["ความซับซ้อนของปมปริศนาอาจต้องใช้สมาธิในการติดตาม", "ตัวละครสมทบบางคนได้พื้นที่ค่อนข้างน้อย"]
    },
    {
        id: "barbie",
        title: "Barbie",
        year: 2023,
        duration: "114 นาที",
        director: "Greta Gerwig",
        cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Issa Rae"],
        genres: ["Comedy", "Fantasy", "Adventure"],
        rating: 79,
        releaseDate: "21 ก.ค. 2023",
        status: "ฉายแล้ว",
        tmdbId: 346698,
        poster:   TMDB + "w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        backdrop: TMDB + "w1280/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
        trailerEmbed: "https://www.youtube.com/embed/pBk4NYhWNMM",
        synopsis: "บาร์บี้ใช้ชีวิตอย่างสมบูรณ์แบบในบาร์บี้แลนด์ จนวันหนึ่งความคิดถึงความตายแทรกเข้ามาในหัว บังคับให้เธอต้องเดินทางสู่โลกมนุษย์จริงเพื่อค้นหาคำตอบ",
        aiReview: "Greta Gerwig แปลงของเล่นที่เป็นที่ถกเถียงเรื่องภาพลักษณ์ผู้หญิงมานานหลายทศวรรษ ให้กลายเป็นหนังตลกที่แฝงการวิพากษ์สังคมปิตาธิปไตยได้อย่างกล้าหาญ MintBot วิเคราะห์ว่างานโปรดักชันดีไซน์สีชมพูจัดจ้านเป็นเปลือกนอกที่ดึงดูดผู้ชมทุกวัย แต่แก่นแท้คือบทพูดเรื่องความกดดันของผู้หญิงในสังคม Ryan Gosling ขโมยซีนในบทเคนได้อย่างไม่คาดคิด",
        pros: ["งานโปรดักชันดีไซน์สีสันสดใสและสร้างสรรค์อย่างน่าทึ่ง", "การแสดงของ Ryan Gosling ในบทเคนที่ขโมยซีน", "บทพูดเสียดสีสังคมที่ตรงประเด็นและกล้าหาญ"],
        cons: ["พยายามพูดถึงประเด็นสังคมหลายเรื่องเกินไปในเวลาจำกัด", "ช่วงท้ายเรื่องสรุปประเด็นค่อนข้างเร่งรีบ"]
    },
    {
        id: "the-substance",
        title: "The Substance",
        year: 2024,
        duration: "141 นาที",
        director: "Coralie Fargeat",
        cast: ["Demi Moore", "Margaret Qualley", "Dennis Quaid"],
        genres: ["Horror", "Sci-Fi", "Drama"],
        rating: 83,
        releaseDate: "20 ก.ย. 2024",
        status: "ฉายแล้ว",
        tmdbId: 933260,
        poster:   TMDB + "w500/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
        backdrop: TMDB + "w1280/cRSin16t8mU7kNHVOjKGiPIFpRD.jpg",
        trailerEmbed: "https://www.youtube.com/embed/--fnb_HFF8U",
        synopsis: "เอลิซาเบธ อดีตดาราดังที่ถูกวงการบันเทิงตัดสินว่าแก่เกินไป ตัดสินใจใช้ยาตลาดมืดลึกลับที่ชื่อ 'The Substance' เพื่อสร้างร่างใหม่ที่อ่อนเยาว์กว่าเดิม",
        aiReview: "Coralie Fargeat สร้างหนังสยองขวัญแนว Body Horror ที่ใช้ความน่าขยะแขยงทางกายภาพเป็นอุปมาเรื่องแรงกดดันด้านความงามที่สังคมกระทำต่อผู้หญิง MintBot วิเคราะห์ว่าการแสดงของ Demi Moore คือกระดูกสันหลังของหนัง เธอกล้าถ่ายทอดความสิ้นหวังของผู้หญิงที่ถูกสังคมตัดสินคุณค่าจากอายุได้อย่างทรงพลัง",
        pros: ["การแสดงของ Demi Moore ที่กล้าหาญและทรงพลังระดับรางวัล", "อุปมาเรื่องแรงกดดันด้านความงามที่ตรงประเด็นและเจ็บแสบ", "งานกำกับภาพและเสียงที่สร้างความอึดอัดได้อย่างมีประสิทธิภาพ"],
        cons: ["ความรุนแรงทางภาพในช่วงท้ายหนักหน่วงมาก ไม่เหมาะกับผู้ชมทุกกลุ่ม", "ข้อความเชิงสังคมบางส่วนถูกกลบด้วยความช็อกทางภาพในช่วงไคลแม็กซ์"]
    },
    {
        id: "challengers",
        title: "Challengers",
        year: 2024,
        duration: "131 นาที",
        director: "Luca Guadagnino",
        cast: ["Zendaya", "Josh O'Connor", "Mike Faist"],
        genres: ["Drama", "Romance", "Sport"],
        rating: 78,
        releaseDate: "26 เม.ย. 2024",
        status: "ฉายแล้ว",
        tmdbId: 937287,
        poster:   TMDB + "w500/oWnxfVvNBU1JwajBmTqKXFgZbJJ.jpg",
        backdrop: TMDB + "w1280/a5vVkqgqcgSK9TZdlNYnYjC3zCp.jpg",
        trailerEmbed: "https://www.youtube.com/embed/EFL-ZuUrBj0",
        synopsis: "ทาชิ อดีตนักเทนนิสดาวรุ่งผู้ผันตัวมาเป็นโค้ช เมื่อสามีของเธอตกอยู่ในช่วงฟอร์มตก เธอจึงส่งเขาลงแข่งในทัวร์นาเมนต์ที่บังคับให้ต้องเผชิญหน้ากับอดีตเพื่อนซี้บนคอร์ตเดียวกัน",
        aiReview: "Luca Guadagnino เปลี่ยนกีฬาเทนนิสให้กลายเป็นอุปมาของความปรารถนาและอำนาจในความสัมพันธ์สามเส้าได้อย่างมีเสน่ห์ MintBot วิเคราะห์ว่าโครงสร้างการเล่าเรื่องแบบสลับเวลาช่วยคลี่คลายความซับซ้อนทางอารมณ์ของตัวละครได้อย่างมีชั้นเชิง ฉากแข่งขันเทนนิสถูกถ่ายทำด้วยมุมกล้องที่สร้างสรรค์และตื่นเต้นราวกับฉากแอ็กชัน",
        pros: ["มุมกล้องและการตัดต่อฉากเทนนิสที่สร้างสรรค์และตื่นเต้น", "ดนตรีประกอบของ Trent Reznor และ Atticus Ross ที่ทรงพลัง", "การแสดงของ Zendaya ที่ซับซ้อนและทรงพลัง"],
        cons: ["ตัวละครชายทั้งสองมีมิติที่ลึกซึ้งน้อยกว่าตัวละครหลัก", "โครงสร้างเวลาที่สลับไปมาอาจทำให้บางคนตามไม่ทันในช่วงแรก"]
    }
];
